### ISSUE TITLE
Code Optimisation

### ISSUE THREAD

**Issue by TheShiveshNetwork** [ManishaSwain8/ReactToWeather#10]
**Describe the bug**
There are many errors going in the terminal that need to be optimized. Like unused variables, etc.

**To Reproduce**
1. Run the app using `npm start`
2. Check the terminal for warnings

**Expected behavior**
The unused variables should be optimized for better performance

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 117.0.5938.134

**Additional context**

The warnings are shown as
```
src\App.js
  Line 1:27:  'createTheme' is defined but never used  no-unused-vars
  Line 3:8:   'axios' is defined but never used        no-unused-vars

src\Components\Home.jsx
  Line 13:10:  'city' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in [eslint]
src\App.js
  Line 1:27:  'createTheme' is defined but never used  no-unused-vars
  Line 3:8:   'axios' is defined but never used        no-unused-vars

src\Components\Home.jsx
  Line 13:10:  'city' is assigned a value but never used  no-unused-vars
```

**Comment by ManishaSwain8** [comment]
Are you getting error or warnings ? @TheShiveshNetwork

**Comment by priyankeshh** [comment]
Can this issue be assigned to me? I can eliminate unused variables, improve code organization, and maintain the readability.

**Comment by ManishaSwain8** [comment]
@TheShiveshNetwork 
@priankeshh

This issue is very minor , Looking forward to some quality issues and PR.
You can create new issue and add this issue along with it so that it will have some weight !

Hope you understand ,Thanks!
