### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by priyankeshh** [ManishaSwain8/ReactToWeather#12]
There are some minor issues with the repo such as:
1. There is the typo "Enetr your city"
2. The API is not called properly
3. The conversion of temperature units is buggy
4. Some variables are uncalled and the code is not much optimized
5. Upon changing the temperature units, the wind speed changes on its own

**Comment by ManishaSwain8** [comment]
@priyankeshh the issues that you have mentioned 1,2,3 is already raised and assigned to others they are working on it ,do check the issues list . 
Moreover issue no 5 that you mentioned ,I am not seeing any changes ,do add a short video on it if your are getting that error .
And the only issue that is a minor one ,
