### ISSUE TITLE
Weather Forecast: Provide a multi-day weather forecast for the selected location.

### ISSUE THREAD

**Issue by Abhii-07** [ManishaSwain8/ReactToWeather#15]
**Is your feature request related to a problem? Please describe.**
Yes, the current application provides current weather data, but users are also interested in having a multi-day weather forecast for the selected location.

**Describe the solution you'd like**
I would like to see a feature added to the application that provides a multi-day weather forecast for the selected location. This would allow users to plan for the upcoming days and make informed decisions based on the expected weather conditions.

**Describe alternatives you've considered**
One alternative could be integrating with a weather API that provides multi-day forecasts. However, it would be more convenient to have this feature built into the application to keep the user experience seamless.

**Additional context**
Adding a multi-day weather forecast feature would enhance the utility of the application and provide users with more comprehensive weather information. It aligns with the user's needs and expectations for planning purposes.

**Comment by Abhii-07** [comment]
Could you please assign it to me? @ManishaSwain8

**Comment by Abhii-07** [comment]
Sure, I'll provide proper comments in the code as well as make a short video.

**Comment by Abhii-07** [comment]
Added the required feature. There was a minor issue in the styling, the background image was a bit small and the multi-day weather cards where coming out of the div so I had to fix that my reducing the size of .container.
Have a look and review so that I create a PR
https://github.com/ManishaSwain8/ReactToWeather/assets/97459166/439e65fa-09cf-4802-8498-81c7b4ccc751

**Comment by ManishaSwain8** [comment]
Lets do one thing , make whole background black in place of image .and keep the height as it is.

@Abhii-07

**Comment by ManishaSwain8** [comment]
If help needed, ping me here !

**Comment by Abhii-07** [comment]
So basically I just created a forecast component and used that in the Home.jsx. Also did some basic styling for the forecast component. Apart from that did no changes to anything else so that the UI part can be optimized/refactored by someone else( If it is already assigned to anyone)

https://github.com/ManishaSwain8/ReactToWeather/assets/97459166/a714c33a-c0f5-4d8c-a004-543daeebb012

**Comment by ManishaSwain8** [comment]
No problem, you can create PR .!

**Comment by Abhii-07** [comment]
Feature implemented and PR merged.
