### ISSUE TITLE
Make it responsive 💫💥

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#18]
Currently it looks weird , add some responsiveness to it keeping the overall structure in mind with UI regulations!
 (TailwindCSS is preferd ) .

**Comment by du1ana** [comment]
would love to work on this. please assign it to me.

**Comment by ManishaSwain8** [comment]
@du1ana go for it !

**Comment by MurtazaShikari** [comment]
@ManishaSwain8 have fixed reponsiveness in the PR if any changes needed do let me know for the same

**Comment by ManishaSwain8** [comment]
@MurtazaShikari sorry to let you know this issue is already assigned to @du1ana , please do not open PR unless you are assigned to that particular issue else PR will not be merged thankyou .

**Comment by ManishaSwain8** [comment]
@du1ana if you are working on it ,for now donot open PR ,as some conflicts are going on with other PR, once done will let you know .

**Comment by MurtazaShikari** [comment]
@ManishaSwain8 Oh I didn't see this sorry for the inconvenience
@du1ana if u need any help do let me know

**Comment by ManishaSwain8** [comment]
@du1ana you can open PR once you are done .Make sure you have the recent code as lot of changes are done already.
