### ISSUE TITLE
🔥Temperature doesn't covert while toggling.

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#2]
Whenever a person toggles on the options to convert to Celsius,Kelvin,etc the temperature doesn't convert. Make sure to use your api and more contributing process are present in readme.md.

Feel free to work on this bug !
Happy coding !😃

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this. Please assign me.

**Comment by ManishaSwain8** [comment]
@IrfanSalim go for it !
