### ISSUE TITLE
Refactor: Code Modularization

### ISSUE THREAD

**Issue by AryanK1511** [ManishaSwain8/ReactToWeather#21]

**Comment by AryanK1511** [comment]
Need to make the code more readable by creating a new Component and breaking down the existing one.

**Comment by ManishaSwain8** [comment]
@AryanK1511 describe your issue . And if possible add SS or video about your changes.

**Comment by ManishaSwain8** [comment]
@AryanK1511 describe your issue . And if possible add SS or video about your changes.
