### ISSUE TITLE
Add Loader for Data Fetching

### ISSUE THREAD

**Issue by Shiba-Tatsuya** [ManishaSwain8/ReactToWeather#23]
**Is your feature request related to a problem? Please describe.**
The current user interface lacks a loader, making it difficult for users to know when data is being fetched.

**Describe the solution you'd like**
I would like to add a loader that is visible while data is being fetched. This loader will provide visual feedback to users, indicating that the application is actively retrieving data.

**Describe alternatives you've considered**
One alternative would be to rely solely on the user interface without a loader. However, this can lead to confusion and a less intuitive user experience.

**Additional context**
Currently, when a user submits a request for weather data, there is no visual indication that the data is being fetched. Adding a loader will improve the user experience by clearly indicating the ongoing data retrieval process.

**Comment by DanielAgbeni** [comment]
Pls assign me to this task

**Comment by ManishaSwain8** [comment]
@Shiba-Tatsuya  I saw the loader you added need some improvement ,
1.Remove the loading text and keep only loader icons.
2.Add purple color to it too to make it look appealing 
3.Before opening PR make sure to add a video .

I have closed the PR you raised as you were not assigned to you and had conflicts to follow best practices .
Now you can add your feature based on the updated code and open PR.

@Shiba-Tatsuya assigning this to you .
