### ISSUE TITLE
UI / UX Optimization

### ISSUE THREAD

**Issue by TheShiveshNetwork** [ManishaSwain8/ReactToWeather#27]
**Describe the bug**
User experience needs optimization.

**To Reproduce**
1. Run the app
2. Enter the city and submit

**Expected behavior**
- A loader should appear while loading data.
- The app has layout shift that should be fixed.
- UI needs to be optimized (adding some custom components to make it look better)
- Few further bug fixes (Fixing console errors on running the app)

**Screenshots**
Layout shift:
![Capture1](https://github.com/ManishaSwain8/ReactToWeather/assets/84664410/1d31e16d-d1f8-4ae9-97e2-693cafc061dd)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Can I work on these issues?

**Comment by TheShiveshNetwork** [comment]
Also do you wish to use Tailwind cdn in production? 
It might give a warning
```
cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
```
Are you okay with it or it needs fix?

**Comment by ManishaSwain8** [comment]
@TheShiveshNetwork  this error happened as background img was short , if you are getting this error after updating the code make sure to ping me here will assign you it to you(make sure to have the updated code as lots of changes are done already) .

And about tailwindCSS , let me know how you want to fix this issue.
