### ISSUE TITLE
New feature requested ! 🐥

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#3]
New features are openly accepted feel free to create issue on new features.

**Comment by ShrutiKolla** [comment]
Hello @ManishaSwain8 May I work on this?

**Comment by ManishaSwain8** [comment]
@ShrutiKolla create a new issue on what new feature you want to add with some ss, videos and details if you can.

**Comment by Webby1015** [comment]
Hey @ManishaSwain8 I propose a new feature that i'd like to add i.e to get location from their browser on top of using longitude and latitude
