### ISSUE TITLE
Loader feature needed for better experience

### ISSUE THREAD

**Issue by MurtazaShikari** [ManishaSwain8/ReactToWeather#32]
**Is your feature request related to a problem? Please describe.**
Yes when there is an API call sometimes it may not get fetched hence a loader is needed for better experience

**Describe the solution you'd like**
Would like to add Loader for smooth user experience while fetching data from api

@ManishaSwain8 Can you assign me this issue

**Comment by ManishaSwain8** [comment]
@MurtazaShikari this issue is already raised in issue #23 , I follow first come first try method ,eventually who have raised the issue first will be assigned , if it is not done in certain days will proceed with assigning the second person and so o.
