### ISSUE TITLE
Add Toaster to give better user experience

### ISSUE THREAD

**Issue by MurtazaShikari** [ManishaSwain8/ReactToWeather#33]
**Is your feature request related to a problem? Please describe.**
Yes, the feature requested is to add a Toaster for the application so that the user can have a better user experience

**Describe the solution you'd like**
I would like to add a toast message when the data is fetched successfully from the api and vice versa when not fetched it will show a message to the user with a good ui giving the user a better experience for the app

@ManishaSwain8 if u can assign me this issue?

**Comment by ManishaSwain8** [comment]
@MurtazaShikari if you have worked on it before can show some examples ,for better understanding.

**Comment by MurtazaShikari** [comment]
I was suggesting for something like this and when we enter something invalid it shows an error as well with a very good ui.
![image](https://github.com/ManishaSwain8/ReactToWeather/assets/114511800/69ba4e3f-ad02-4ecc-99fd-f65f59e2bb32)
![image](https://github.com/ManishaSwain8/ReactToWeather/assets/114511800/efd07d06-42f2-4198-af42-0639a8d9f9b7)

**Comment by MurtazaShikari** [comment]
@ManishaSwain8 do check and let me know would be happy to help

**Comment by ManishaSwain8** [comment]
@MurtazaShikari for each condition there is error handling and alerts so ,you need to keep it mind and work accordingly .

You can go for it ! 
Before PR make sure send a video if everything working fine!
