### ISSUE TITLE
🌟Update existing UI /UX.🌟

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#38]
Currently this looks weird and needs some proper alignments and updates.(Tailwind CSS preferred )
In the below image its not properly aligned ,suggest your ideas with images and examples.

![Screenshot (213)](https://github.com/ManishaSwain8/ReactToWeather/assets/96622693/58b3753d-1e6e-4fea-a3f4-ec749d597d84)
  
This is the content you get after adding city or geo location (No changes required in content)

![Screenshot (214)](https://github.com/ManishaSwain8/ReactToWeather/assets/96622693/808bb9d2-ce9d-4b62-a6ea-8d7fc22274de)

**Comment by mhamzanadeem** [comment]
@ManishaSwain8   I am participating in hacktoberfest . Can you assign me this issue .

**Comment by mhamzanadeem** [comment]
@ManishaSwain8  Can u tell me why it is not giving me weather of specfic city .  I clicked on "get weather "  , it is not giving me  updates 

![77777](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/c3121fd0-9286-45fc-bc1d-76351a296657)

**Comment by ManishaSwain8** [comment]
@mhamzanadeem please give some examples or screenshots or images how you want to change this UI.

 And the data will not appear because as the data limits may crossed so you have to use your own api in the code.
Please prefer readme.md to get info about api.

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem please give some examples or screenshots or images how you want to change this UI.
> 
>  And the data will not appear because as the data limits may cross per day/month/year , so you have to use your own api in the code.
> Please prefer readme.md to get info about api.

Ok . 
I will read readme.md

**Comment by mhamzanadeem** [comment]
@ManishaSwain8 
I have these changes in my mind regarding alignment . 
Also , we can apply the picture at the background 
 
Can You share some ideas of what kind of changes do u want to bring in your app in UI
![273434122-58b3753d-1e6e-4fea-a3f4-ec749d597d84](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/5a1a37a2-5915-48d8-860a-cac74828b2e8)

**Comment by ManishaSwain8** [comment]
@mhamzanadeem you can go ahead !Make sure to update the code as some recent changes has been done already.

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem you can go ahead !Make sure to update the code as some recent changes has been done already.
@ManishaSwain8 assign me the issue

**Comment by ManishaSwain8** [comment]
@mhamzanadeem before pull req make sure to add a video .

**Comment by mhamzanadeem** [comment]
@ManishaSwain8 

Is this picture good as a background of website ?
Or you recommend to keep this black background (as it having now)

![Screenshot_2023-10-09-00-24-21-008_com.android.chrome-edit.jpg](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/2c18501c-fd95-43bf-9ed0-b0412cfcd04f)

**Comment by ManishaSwain8** [comment]
@mhamzanadeem no need , it is assigned to some else..you are required to work on the issue that have been assigned to you.

**Comment by ManishaSwain8** [comment]
Is it responsive ? @mhamzanadeem

**Comment by mhamzanadeem** [comment]
> Is it responsive ? @mhamzanadeem
@ManishaSwain8  
does it looks good ? 
![8898](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/8f7a3778-91c8-4379-9c49-fc3a171e1efb)

**Comment by ManishaSwain8** [comment]
Another query ,when switched to lat and lon in the drop down (geolocation) 2 input box appears , are they looking fine too ?
@mhamzanadeem

**Comment by mhamzanadeem** [comment]
> Another query ,when switched to lat and lon in the drop down (geolocation) 2 input box appears , are they looking fine too ? @mhamzanadeem

@ManishaSwain8 Does it looks good?

![1](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/2736f7a5-15da-4432-b143-b4f85cde0446)
![2](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/99d610a1-a31a-4e19-88c4-0b5b97b4fa5a)

**Comment by ManishaSwain8** [comment]
@mhamzanadeem cool !
You can open PR will review it soon .

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem cool ! You can open PR will review it soon .

@ManishaSwain8  i am facing issue  that wather details is not in center of page , but it is center in page in mobile view 
secondly ,  I use the API key , but it is not diaplaying flashcards in large and small devices both . In that situation , what I do ? Should i make a pull request?
![4](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/d6a13814-7e48-4ce5-95ea-4889cca083c7)
![5](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/56a03afd-8462-4072-9d3b-21f1a5eff8df)

**Comment by ManishaSwain8** [comment]
As per the current code everything is working fine , may be you have added some styling that is affecting others too, so no need to make responsive you can just add alignment for buttons and input fields for desktop view, and try to use margin-top/buttom very less cause use them independently causes other components to lose alignment ,try to create universal.
@mhamzanadeem

**Comment by mhamzanadeem** [comment]
@ManishaSwain8  I Have fixed UI .  You can see the screenshots , I tried to upload vide0 , but it was 60 mb . So it couldnot upload .
If you like my contribution , So can i make PR ?
![1](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/fc9f663a-47fe-481a-861b-98af4d11796f)
![2](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/930b61b8-d276-4994-9350-b059aae64dd9)
![3](https://github.com/ManishaSwain8/ReactToWeather/assets/114602354/88d5ad93-108d-46eb-a3e5-e3593bb9dd61)

**Comment by ManishaSwain8** [comment]
@mhamzanadeem sure go ahead and add PR , I will do the review.
