### ISSUE TITLE
Change background as per weather.☔

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#41]
The image in the background image must change as per the weather ,but not the whole background just the inner box background.

If, as currently the description text is white , you can make necessary changes as per background (can add glassmorphic effect )

**Comment by du1ana** [comment]
wow, this is a cool addition. i'd like to work on it. assign me please

**Comment by Albert-2** [comment]
yeess actually it is a greate idea and sure i love to contribute.. please assign me this issue....
Thank You... :)

**Comment by akum4r** [comment]
can i contribute to it please?

**Comment by ManishaSwain8** [comment]
@du1ana has showed interest first so will go with him.This repo follows,those who  comes first they will be assigned to the issue.If this issue is not resolved by particular person in limited time then the issue will be assigned to person who commented next ..and so on.

@Albert-2 and @akum4r  you can look for new issues 
Thanks

**Comment by ManishaSwain8** [comment]
@du1ana you can go ahead but in your previous PR you have reduced the height of the inner box , please change it  into original height.
And make sure to put video before opening PR .
