### ISSUE TITLE
Fix API Calls for Weather Information

### ISSUE THREAD

**Issue by M-A-N-I-K** [ManishaSwain8/ReactToWeather#43]
Problem:
While we have successfully integrated the Weather API into our web project to provide users with real-time weather information, we are currently facing an issue where the API calls are not functioning as expected. This is preventing us from displaying accurate weather data to our users.

![image](https://github.com/ManishaSwain8/ReactToWeather/assets/95385759/3a5247de-9648-4b44-ae67-93c3174862b6)

Proposed Resolution:
To resolve this issue, we need to investigate and address the root cause of the API call failures. We should ensure that our API requests are properly configured, that we are handling responses correctly, and that any potential errors are being handled gracefully.

Proposed Changes:

    Review the current API call implementation to identify any misconfigurations or issues.
    Implement necessary changes to ensure the API calls are correctly formatted and authenticated.
    Handle API responses and errors appropriately to prevent failures from affecting the user experience.

**Comment by M-A-N-I-K** [comment]
I would like to work on this issue myself

**Comment by Arnav7107** [comment]
Hi @M-A-N-I-K  is it fine if I try to solve this issue? Can you assign it to me?

**Comment by du1ana** [comment]
hi, @M-A-N-I-K did you generate a valid API key from OpenWeatherMap and replace the[ apiKey on Home.jsx](https://github.com/ManishaSwain8/ReactToWeather/blob/e631a1c43ce9d513f92196390565d3389c513761/src/Components/Home.jsx#L19)?

**Comment by ManishaSwain8** [comment]
@M-A-N-I-K as don't see any problem make sure to make a video on it , and do follow @du1ana suggestions

**Comment by M-A-N-I-K** [comment]
@du1ana I am talking about link in the github description. That is not working. Then maybe there is something wrong with deployment

**Comment by M-A-N-I-K** [comment]
@ManishaSwain8 But whats the point if a non developer wont be able to use it ? It should be accessible on deployed link too!!

**Comment by ManishaSwain8** [comment]
Yeah that true ,will be finding some alternatives to it ,if you have any suggestion feel free to add here and will assign it to you.
