### ISSUE TITLE
Add docker capability

### ISSUE THREAD

**Issue by ron-huberfeld** [ManishaSwain8/ReactToWeather#44]
This project requires installation of the following prerequisites on the developer computer - 
![image](https://github.com/ManishaSwain8/ReactToWeather/assets/32178925/cf1db341-021f-424c-b000-305388153344)
This is prone to problems since installation might be different in different PCs.

Docker enable a way to containerized the development environment and the deployed product.

I suggest to docker build the project like this video suggests - 
https://www.youtube.com/watch?v=8VHheCkw-7k

* Note that the old way will still work

**Comment by ron-huberfeld** [comment]
Hi @ManishaSwain8 
Please have a look at this issue suggestion, approve it and assign me.
Thanks

**Comment by ManishaSwain8** [comment]
@ron-huberfeld ,will let you know soon .
