### ISSUE TITLE
Contributors in Readme.md file

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [ManishaSwain8/ReactToWeather#45]
In the screenshot below, you can see that only one contributor is displayed. 

![Screenshot 2023-10-09 112744](https://github.com/ManishaSwain8/ReactToWeather/assets/102857774/ccdf89ba-f002-425c-816f-46dad5e3b8d3)

I want to fix this by dynamically adding all the contributors of this project to the README.md file.

**Comment by ManishaSwain8** [comment]
@Pinaka-Pani-18 that's my image added purposely to express my thanks to all contributors, no need to add this feature as one contributors are displayed already through github features .
And it will be just one line of html code req, this repo is looking forward to some quality issues and PR that can help the project to improve .
 
Feel free to search some new issue.
Thanks for your interest !
