### ISSUE TITLE
Add a navbar in the header section.

### ISSUE THREAD

**Issue by Aarav238** [ManishaSwain8/ReactToWeather#46]
**Is your feature request related to a problem? Please describe.**
Without navbar website doesn't look good. Navbar is present in every website

**Describe the solution you'd like**
I want to add a navbar in it with a title `ReactToWeather`

![image](https://github.com/ManishaSwain8/ReactToWeather/assets/95538627/d83236dd-6f19-4232-be89-62b215d30619)

**Comment by Aarav238** [comment]
Please assign this to me @ManishaSwain8

**Comment by ManishaSwain8** [comment]
@Aarav238 go for it.

Display title in left side and in right side add Home ,Converter, Features (with drop down icon)
Make sure its responsive (if possible add hamburger icon)

**Comment by ManishaSwain8** [comment]
@Aarav238 what's the update ?

**Comment by its-kumar-yash** [comment]
@ManishaSwain8 Please assign this to me, I want to work on this issue

**Comment by its-kumar-yash** [comment]
@ManishaSwain8 Please review this.
Video Link : https://drive.google.com/file/d/1xxKdKC1V0m0jRnPjdsJnKu8YJWeCHofm/view?usp=sharing

**Comment by ManishaSwain8** [comment]
@its-kumar-yash as this is already assigned to @Aarav238 he has been working on it , if this was not solved then will assign it to you.
Thanks for your interest.

**Comment by ManishaSwain8** [comment]
@Aarav238 Please give your update .

**Comment by Aarav238** [comment]
Hey I’ll raise PR by today. Sorry for delay!

**Comment by ManishaSwain8** [comment]
@Aarav238 no problem

**Comment by Aarav238** [comment]
Hey @ManishaSwain8  I have added icon , title , home , converter and some hover effect and I don't think there is any need to add features in the header section as it  will not look good , for that you can make another section of page . by seeing the application we got to know about the features of the web app , So i would suggest to keep the navbar simple and unform with your application .
![image](https://github.com/ManishaSwain8/ReactToWeather/assets/95538627/ea182fa3-c42c-4cd3-ac44-0701d48d925c)
