### ISSUE TITLE
Update TailwindCSS configuration .⚠️

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#48]
Remove use of cdn.tailwindCSS and upadate module.export in tailwind.config.js.

As currently the cdn link is used in root index.html to trigger the tailwindCss properties, 

Warning found:
 cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI:

No need of PostCSS, only update Tailwind CLI.

**Comment by Petsamuel** [comment]
kindly assign this task to me

**Comment by Petsamuel** [comment]
kindly assign this task to me

**Comment by nobledeveloper01** [comment]
assign me to this task pls

**Comment by ManishaSwain8** [comment]
@Petsamuel you can go ahead !

**Comment by ManishaSwain8** [comment]
@nobledeveloper01 this repo follows first come first try ,person who comments first will be assigned.

Feel free to create new issues .
