### ISSUE TITLE
Docs: Missing PR template

### ISSUE THREAD

**Issue by inkollusireeshaadharani** [ManishaSwain8/ReactToWeather#5]
**Is your feature request related to a problem? Please describe.**
The project does not have a PR template 

**Describe the solution you'd like**
A good PR template needs to be added for making Pull requests easier for everyone. 

**Additional context**
I would love to add a PR template if the issue is assigned to me

**Comment by ManishaSwain8** [comment]
New feature means if any additional functionality one can add like getting weather through geo location ,etc ,Currently the data is fetched using city name.

I agree PR template is required, so go for it !

**Comment by inkollusireeshaadharani** [comment]
> New feature means if any additional functionality one can add like getting weather through geo location ,etc ,Currently the data is fetched using city name.

thank you for clarifying
