### ISSUE TITLE
Add preloader to website 🔴

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#50]
As the application grows eventually it will take time to load ,so a loader required (recommended package: react-loader /spinner)

**Comment by killerkc12** [comment]
@ManishaSwain8 I would like to work on this. If you're ok, please assign to me

**Comment by ManishaSwain8** [comment]
Sure go ahead ! But make sure to add video before opening PR.

**Comment by killerkc12** [comment]
@ManishaSwain8 Could you please look into this. Request is response with Unauthorized status code on https://react-to-weather.vercel.app/
![image](https://github.com/ManishaSwain8/ReactToWeather/assets/50802786/ac4f1e0c-3525-46c5-9323-8ff9692d1ab1)

**Comment by ManishaSwain8** [comment]
@killerkc12 the link in the description will not show content because you have to use your own API key in Home.jsx after forking the project .Make sure to read README.md file for more details.

**Comment by TheShiveshNetwork** [comment]
Assign this to me too!

**Comment by ManishaSwain8** [comment]
@TheShiveshNetwork this issue is already assigned to @killerkc12 
You can go ahead with new issue .

**Comment by ManishaSwain8** [comment]
@killerkc12 any update !

**Comment by killerkc12** [comment]
@ManishaSwain8 Changes are done, I'll give the video with PR tomorrow

**Comment by killerkc12** [comment]
@ManishaSwain8 Please check the video below. Let me know if any changes required

https://github.com/ManishaSwain8/ReactToWeather/assets/50802786/50020338-1b78-4a92-bf1c-dd9c9e358b9d
