### ISSUE TITLE
Add voice recognition search 🌟

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#55]
Implement the search functionality using voice .

**Comment by y-ashaswini** [comment]
Hey! I've had experience with web and related js frameworks, I believe I can work on this functionality. Please assign this issue to me!

**Comment by ManishaSwain8** [comment]
Sure @y-ashaswini  go ahead.

**Comment by y-ashaswini** [comment]
hey @ManishaSwain8 ! Are you going to give me an API key to work with? Or is it commented out somewhere in the code?
