### ISSUE TITLE
Feature : Map add for location

### ISSUE THREAD

**Issue by Hardik2972** [ManishaSwain8/ReactToWeather#59]
**Is your feature request related to a problem? Please describe.**
A  I want to add the map so that anyone can get the weather report just with the help of pointer like this 

![Screenshot 2023-10-18 230049](https://github.com/ManishaSwain8/ReactToWeather/assets/115338787/e6932dca-e486-47bf-a25b-1357ca6a2c9c)
 
Can I add this feature

**Comment by ManishaSwain8** [comment]
@Hardik2972 can you add a video for better clarification !

**Comment by Hardik2972** [comment]
yes of course.

**Comment by ManishaSwain8** [comment]
@Hardik2972 it looks so cool , please go ahead !
