### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by uddiptojana10** [ManishaSwain8/ReactToWeather#6]
**Describe the bug**
Minor spelling error 

**To Reproduce**
1. Go to home page
2. Spelling error can be seen on the placeholder to search for cities

Screenshot:
![scrnli_10_7_2023_9-14-34 AM](https://github.com/ManishaSwain8/ReactToWeather/assets/117717963/6fc8be9a-cec0-4a69-87c9-61157807bd02)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave,Chrome
 - Version: 2H22

**Smartphone (please complete the following information):**

**Comment by ManishaSwain8** [comment]
It's good you pointed out but looking forward to quality PRs.

Thanks! 
You can contribute to any other issue and add this issue with it too , thankyou for understanding!
