### ISSUE TITLE
Adjust breakpoints for buttons "Get Weather" and "Show Forecast"

### ISSUE THREAD

**Issue by gabrielpoetaa** [ManishaSwain8/ReactToWeather#62]
Hi, 
I've noticed the buttons _Get Weather and _Show Forecast_ are not wrapping accordingly. Between widths of 1073px-770px the buttons are actually disappearing on screen. I believe they should move somewhere below the search bar along with the mic icon so the responsiveness of the application is not prejudiced. 

Video link of the issue: https://streamable.com/f66psi

I'd like to work on this issue, if possible. 

PS.: liked this app very much, didn't have time to dig into its architecture, still it looks pretty nice. Good job!

**Comment by ManishaSwain8** [comment]
@gabrielpoetaa 
Yes I have noticed this issue , please go ahead assigning it to you !
