### ISSUE TITLE
Footer section in the bottom of the web-application .

### ISSUE THREAD

**Issue by abhay-raj19** [ManishaSwain8/ReactToWeather#64]
**Is your feature request related to a problem? Please describe.**
there is only a black screen at the bottom of the page and want to make and update a good footer section that will help the user contact the owner of the project for such type of web applications. 

**Describe the solution you'd like**
will add a simple footer section in the bottom ,

I have 2  options :
1. a simple footer in which I will mention created by ❤️by @ManishaSwain8 
2. Footer section with all the contact us ,about us and etc .

**Describe alternatives you've considered**
or mention a new and alternative way for the footer section , I will update that also.

Pls assign me for the above mentioned changes 
and after completing up the I will raise up the PR ASAP.

Label it with Hacktoberfest tag.

**Comment by ManishaSwain8** [comment]
@abhay-raj19 sure go ahead .
But no need to mention my name, in place mention Open source community
