### ISSUE TITLE
Add temperature converter calculator 

### ISSUE THREAD

**Issue by ManishaSwain8** [ManishaSwain8/ReactToWeather#65]
Add a temp converter ,in new page and the redirect  option is given in navbar "Converter"  ,
Add converter with dropdown icon, having dropdown options  like
-Celsius
-Kelvin 
-Fahrenheit

 It must have an input field ,drop down and result field

keeping color scheme in mind *

**Comment by Mausoomi12** [comment]
I would like to work on this issue and get to learn stuff along the way. Kindly assign this one to me.

**Comment by Hardik2972** [comment]
I would like to contribute in this can you please assign it to me

**Comment by ManishaSwain8** [comment]
@harshvyas-22 you can go ahead .

**Comment by ManishaSwain8** [comment]
@Mausoomi12 and @Hardik2972  as in this repo , whoever comments first in issue will be assigned to that issue .
If this issue not gets solved in particular  time then it will ne passed on to the person who commented next and so on.

You guys can search for new issues ! : )

**Comment by ManishaSwain8** [comment]
@Mausoomi12 please go ahead !
