### ISSUE TITLE
error in searching up the lattitude and longitude as well as city name.

### ISSUE THREAD

**Issue by abhay-raj19** [ManishaSwain8/ReactToWeather#69]
**Describe the bug**
While running up the same project locally there are details of weather being listed up while running the same project on vercel deployment there are error being raised up .

![image](https://github.com/ManishaSwain8/ReactToWeather/assets/96302417/d46e3da3-8b39-4278-9c6d-4faeb09cacba)
![image](https://github.com/ManishaSwain8/ReactToWeather/assets/96302417/77b653a6-4acf-499f-9392-cb660526aa26)

Assign me this issue and label it under `Hacktoberfest` ASAP.

**Comment by ManishaSwain8** [comment]
As the API key is hidden , it will not be visible but will run in local
