### ISSUE TITLE
Button to get location 

### ISSUE THREAD

**Issue by Webby1015** [ManishaSwain8/ReactToWeather#70]
Add a Button to Take Users Longitude and Latitude form it's browser location

**Comment by ManishaSwain8** [comment]
There is similar feature in this project , if you have something new make sure to add video for clarification : )

**Comment by ManishaSwain8** [comment]
@Webby1015 go ahead

**Comment by Webby1015** [comment]
Sure, Since i Don't have the api Key for this project, i'll just add a button that console.logs the coordinates 

> @Webby1015 go ahead

Sure, Since i Don't have the api Key for this project, i'll just add a button that console.logs the coordinates
