### ISSUE TITLE
Getting weather details through geolocation

### ISSUE THREAD

**Issue by uddiptojana10** [ManishaSwain8/ReactToWeather#8]
A feature where user can enter latitude and longitude coordinates to get weather details.

 I am willing to contribute on this if assigned. Additionally, I have fixed the minor spelling error and temperature toggling issue.

**Comment by ManishaSwain8** [comment]
@uddiptojana10  go for it !

**Comment by ManishaSwain8** [comment]
Make sure a person have independency of choosing if he/she wants to get weather as per city or geo location.
You can add toggle or dropdown.

**Comment by ManishaSwain8** [comment]
@uddiptojana10 do not work on temperature toggling issue as already it is assigned to someone else .
You can work on , geo location and spelling .

**Comment by uddiptojana10** [comment]
oh okay.
