### ISSUE TITLE
Adding localisation support for the react application

### ISSUE THREAD

**Issue by deathsurgeon1** [ManishaSwain8/ReactToWeather#9]
**Is your feature request related to a problem? Please describe.**
As of now the app supports only english language. We can further enhance this and support multiple other languages via localisation integration.

**Describe the solution you'd like**
Add Localization to React App with react-i18next 

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by deathsurgeon1** [comment]
Hi @ManishaSwain8 please have a look at above feature request and let me know if this will be a helpful feature.

**Comment by ManishaSwain8** [comment]
@deathsurgeon1 it sounds interesting but how can this help enhance this project , give some more insights ! 
And will it  be applicable through keyboard of laptop or desktop ?
